# Generated by Django 5.1.6 on 2025-02-12 17:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('parent_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('parent_phone_number', models.CharField(max_length=13)),
                ('parent_email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(upload_to='students/')),
                ('grade', models.CharField(choices=[('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], max_length=2)),
                ('gender', models.CharField(choices=[('mal', 'Male'), ('fem', 'Female'), ('gay', 'GAY')], max_length=3)),
                ('status', models.CharField(choices=[('ac', 'Active'), ('in', 'Inactive'), ('pd', 'Pending')], default='in', max_length=2)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='groups.group')),
                ('subjects', models.ManyToManyField(related_name='students', to='subjects.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
