# Generated by Django 5.1.6 on 2025-02-12 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=30)),
                ('max_students', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ac', 'Active'), ('in', 'Inactive'), ('pd', 'Pending')], max_length=2)),
                ('grade_level', models.CharField(choices=[('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], max_length=2)),
                ('schedule', models.CharField(choices=[('mr', 'Morning Session'), ('af', 'Afternoon Session'), ('ev', 'Evening Session')], default='in', max_length=2)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('subjects', models.ManyToManyField(blank=True, related_name='groups', to='subjects.subject')),
                ('teacher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='teachers.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
