# Generated by Django 5.1.6 on 2025-02-13 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='attendance',
            field=models.PositiveIntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
